### ISSUE TITLE
Disable swiping

### ISSUE THREAD

**Issue by topclaudy** [lifelynl/angular-carousel#4]
How do I disable swiping?

**Comment by jessedvrs** [comment]
I'm afraid that's not yet possible. I will put it on the todo list :) expect it soon.
thanks

**Comment by Hani-Ghazi** [comment]
Hi @jessedvrs 
Have you implemented this feature? cause in the demo the swipe is disabled, but yet I can archive this in my project ...

**Comment by jessedvrs** [comment]
@Hani-Ghazi I didn't, for me swiping works in the demo
